interface Marker {
    city:string,
    coordinates: [number, number]
}


export const markers: Marker[] = [
    {city: 'Aachen', coordinates: [50.7753, 6.0839]},
    {city: 'Augsburg', coordinates: [48.3705, 10.8978]},
    {city: 'Bergisch Gladbach', coordinates: [50.9896, 7.1230]},
    {city: 'Berlin', coordinates: [52.5200, 13.4050]},
    {city: 'Bielefeld', coordinates: [52.0302, 8.5325]},
    {city: 'Bochum', coordinates: [51.4818, 7.2162]},
    {city: 'Bonn', coordinates: [50.7374, 7.0982]},
    {city: 'Bottrop', coordinates: [51.5291, 6.9447]},
    {city: 'Bremen', coordinates: [53.0793, 8.8017]},
    {city: 'Bremerhaven', coordinates: [53.5396, 8.5809]},
    {city: 'Brunswick', coordinates: [31.1500, 81.4915]},
]



let allCities = [
    "Aachen",
    "Augsburg",
    "Bergisch Gladbach",
    "Berlin",
    "Bielefeld",
    "Bochum",
    "Bonn",
    "Bottrop",
    "Bremen",
    "Bremerhaven",
    "Brunswick",
    "Chemnitz",
    "Cologne",
    "Cottbus",
    "Darmstadt",
    "Dortmund",
    "Dresden",
    "Duisburg",
    "Dusseldorf",
    "Erfurt",
    "Erlangen",
    "Essen",
    "Frankfurt am Main",
    "Freiburg",
    "Furth",
    "Gelsenkirchen",
    "Gottingen",
    "Hagen",
    "Halle",
    "Hamburg",
    "Hamm",
    "Hanover",
    "Heidelberg",
    "Heilbronn",
    "Herne",
    "Hildesheim",
    "Ingolstadt",
    "Jena",
    "Karlsruhe",
    "Kassel",
    "Kiel",
    "Koblenz",
    "Krefeld",
    "Leipzig",
    "Leverkusen",
    "Ludwigshafen",
    "Lübeck",
    "Magdeburg",
    "Mainz",
    "Mannheim",
    "Moers",
    "Monchengladbach",
    "Mulheim",
    "Munich",
    "Munster",
    "Neuss",
    "Nuremberg",
    "Oberhausen",
    "Offenbach",
    "Oldenburg",
    "Osnabruck",
    "Paderborn",
    "Pforzheim",
    "Potsdam",
    "Recklinghausen",
    "Regensburg",
    "Remscheid",
    "Reutlingen",
    "Rostock",
    "Saarbrucken",
    "Salzgitter",
    "Siegen",
    "Solingen",
    "Stuttgart",
    "Trier",
    "Ulm",
    "Wiesbaden",
    "Wolfsburg",
    "Wuppertal",
    "Wurzburg",
]